import type { AnalysisResult } from "./schema";

function csvCell(value: string | number) {
  const text = String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function exportFeedbackCsv(result: AnalysisResult): string {
  const header = [
    "student_id",
    "status",
    "misconception_cluster",
    "confidence",
    "student_friendly_feedback",
    "next_step",
  ];
  const misconceptionLabels = new Map(
    result.misconceptions.map((item) => [item.id, item.title]),
  );
  const rows = result.students.map((student) => [
    student.studentId,
    student.status,
    student.misconceptionId
      ? misconceptionLabels.get(student.misconceptionId) ?? student.misconceptionId
      : "",
    Math.round(student.confidence * 100),
    student.studentFeedback,
    student.nextStep,
  ]);
  return [header, ...rows].map((row) => row.map(csvCell).join(",")).join("\n");
}

export function exportTeacherMarkdown(result: AnalysisResult): string {
  const lines = [
    "# Misconception Map — Teacher Report",
    "",
    `**Subject:** ${result.assignmentSummary.subject}`,
    `**Grade:** ${result.assignmentSummary.gradeLevel}`,
    `**Learning objective:** ${result.assignmentSummary.learningObjective}`,
    "",
    "## Class overview",
    "",
    result.overview.oneSentenceSummary,
    "",
    `- Responses analyzed: ${result.overview.totalResponses}`,
    `- Correct or mostly correct: ${result.overview.correctCount + result.overview.nearCorrectCount}`,
    `- Responses showing a misconception: ${result.overview.misconceptionCount}`,
    `- Unclear responses: ${result.overview.unclearCount}`,
    "",
    "## Misconception patterns",
    "",
  ];

  for (const item of result.misconceptions) {
    lines.push(
      `### ${item.title} (${item.percentOfClass}% of class)`,
      "",
      item.description,
      "",
      `**Students:** ${item.studentIds.join(", ")}`,
      `**Likely reasoning:** ${item.likelyReasoning}`,
      `**Why this matters:** ${item.instructionalRisk}`,
      `**Suggested teacher move:** ${item.teacherMove}`,
      `**Confidence:** ${Math.round(item.confidence * 100)}%`,
      "",
      "**Evidence from student work**",
      "",
      ...item.evidenceQuotes.map(
        (evidence) => `- ${evidence.studentId}: “${evidence.quote}”`,
      ),
      "",
      "**Targeted practice**",
      "",
      ...item.practiceQuestions.map(
        (practice, index) =>
          `${index + 1}. ${practice.question} — Answer: ${practice.expectedAnswer} (${practice.purpose})`,
      ),
      "",
    );
  }

  lines.push(
    "## Tomorrow's plan",
    "",
    result.reteachingPlan.tomorrowPlan,
    "",
    "### 10-minute mini lesson",
    "",
    `**Objective:** ${result.reteachingPlan.tenMinuteMiniLesson.objective}`,
    `**Board example:** ${result.reteachingPlan.tenMinuteMiniLesson.boardExample}`,
    "",
    ...result.reteachingPlan.tenMinuteMiniLesson.teacherScript.map(
      (step, index) => `${index + 1}. ${step}`,
    ),
    "",
    `**Check for understanding:** ${result.reteachingPlan.tenMinuteMiniLesson.checkForUnderstanding}`,
    "",
    "### Exit ticket",
    "",
    result.reteachingPlan.exitTicket.prompt,
    "",
    `**Answer:** ${result.reteachingPlan.exitTicket.correctAnswer}`,
    "",
    "## Guardrails",
    "",
    ...result.limitations.map((item) => `- ${item}`),
    "",
    "_Generated by Misconception Map. Teacher review required._",
  );

  return lines.join("\n");
}

